---
     - name: "install marysiaDb"
       yum:
         name: "{{packages}}"
         state: present
       vars:
         packages:
            - mariadb
            - mariadb-server
     - name: "PHP-mysql"
       yum:
         name: "{{packages}}"
         state: latest
       vars:
         packages:
            - php-mysql
            - MySQL-python
     - name: "start mariadb"
       service: 
         name: mariadb
         state: started 
     - name: "create db user"
       mysql_user:
           name: "root"
           password: ""
           priv: '*.*:ALL'
           state: present
           host: '%'     
         
     - name: "create new db"
       mysql_db:
           name: "{{db_name}}"
           state: present
     - name: "copy db"
       copy:
           src: templates/{{db_name}}.sql
           dest: /tmp/{{db_name}}.sql
     - name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
       mysql_db:
           state: import
           name: carrental
           target: /tmp/{{ db_name }}.sql
    

